version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: delivery_postgres
    restart: always
    environment:
      POSTGRES_DB: marvisareparto
      POSTGRES_USER: marvisadbuser
      POSTGRES_PASSWORD: 9bTi5SuF1OY6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: delivery_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/delivery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
      APP_JWT_ACCESS_EXPIRATION: 900000
      APP_JWT_REFRESH_EXPIRATION: 604800000
    ports:
      - "8080:8080"

volumes:
  postgres_data: